version: '3.8'

services:
  # Keryx
  keryx:
    image: node:latest
    container_name: keryx-nvn-io
    network_mode: 'host'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=32790
    working_dir: /app
    volumes:
      - /share/MediaOne/www/keryx.nvn.io:/app
      - /share/MediaOne/www/assets:/app/assets:ro
    command: sh -c "npm install && node assets/js/server.js"

  # JustinBehanna.com/net/org
  justinbehanna:
    image: node:latest
    container_name: justinbehanna-xxx
    network_mode: 'host'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=32792
    working_dir: /app
    volumes:
      - /share/MediaOne/www/justinbehanna.xxx:/app
      - /share/MediaOne/www/assets:/app/assets:ro
    command: sh -c "npm install && node assets/js/server.js"

  nihiven:
    image: node:latest
    container_name: nihiven-xxx
    network_mode: 'host'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=32793
    working_dir: /app
    volumes:
      - /share/MediaOne/www/nihiven.xxx:/app
      - /share/MediaOne/www/assets:/app/assets:ro
    command: sh -c "npm install && node assets/js/server.js"

  glitchrock:
    image: node:latest
    container_name: glitchrock-xxx
    network_mode: 'host'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=32794
    working_dir: /app
    volumes:
      - /share/MediaOne/www/glitchrock:/app
      - /share/MediaOne/www/assets:/app/assets:ro
    command: sh -c "npm install && node assets/js/server.js"

  samus-cam:
    image: node:latest
    container_name: samus-cam
    network_mode: 'host'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=32795
    working_dir: /app
    volumes:
      - /share/MediaOne/www/samus.cam:/app
      - /share/MediaOne/www/assets:/app/assets:ro
    command: sh -c "npm install && node assets/js/server.js"

  clips:
    image: node:20-slim
    container_name: clips-jeb-rip
    network_mode: 'host'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=32796
      - LIBVA_DRIVER_NAME=iHD
    working_dir: /app
    volumes:
      - /share/MediaOne/www/clips.jeb.rip:/app
    devices:
      - /dev/dri:/dev/dri
    command: sh -c "apt-get update && apt-get install -y ffmpeg vainfo intel-media-va-driver && npm install && mkdir -p uploads transcoded thumbnails && chmod 777 uploads transcoded thumbnails && node server.js"
